### ISSUE TITLE
Please add in the readme where to report issues with the images. 

### ISSUE THREAD

**Issue by mzdaniel** [manjaro-arm/pbpro-images#1]
Thank you for adding this github resource.

The latest  [Dev 20210719](https://github.com/manjaro-arm/pbpro-images/releases/tag/20210719) keeps the pinebookpro screen completely black the whole time, from power-on all the way to login, making the image useless and wasting time and resources for everyne. I suspect this critical issue is an overlooked regression somewhere.

Can we add add in the README.md of this repo where to report issues that will be looked by maintainers?

**Comment by Strit** [comment]
Which of the images have you tried?

I tried the Plasma image earlier this week and that worked fine. It just takes a little while to start the UI.

Issues for the dev images are fine to be reported here I think or in the forum.

If you even know what package has the issue, you can report it on our gitlab repository for that package.

**Comment by mzdaniel** [comment]
Sounds good and thank you for looking into this @Strit.
Turned out there was an incompatibility issue with a previous U-Boot that prevented Manjaro-ARM-minimal-pbpro-20210719.img to boot. At last, I upgraded U-Boot on it and the image does boot as expected.
Closing this issue
